# Generated by Django 5.0.4 on 2024-05-01 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Permiso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Permisos',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('contrasena', models.CharField(max_length=50)),
                ('mail', models.CharField(max_length=50)),
                ('telefono', models.DecimalField(decimal_places=0, max_digits=10)),
                ('fechaNacimiento', models.DateField()),
            ],
            options={
                'verbose_name_plural': 'Usuarios',
            },
        ),
        migrations.CreateModel(
            name='Permiso_usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permiso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminUsuario.permiso')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminUsuario.usuario')),
            ],
            options={
                'verbose_name_plural': 'Permisos por usuarios',
            },
        ),
    ]
